// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5A9CwlZl2Xj7gR9ghkm2VjO64ThgIV-I',
    appId: '1:893498280126:web:d0d4dd4bed881852db76ef',
    messagingSenderId: '893498280126',
    projectId: 'lifediary-8badd',
    authDomain: 'lifediary-8badd.firebaseapp.com',
    storageBucket: 'lifediary-8badd.appspot.com',
    measurementId: 'G-RKFZ2DBY9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGxRg0b3cPpJbTouoy9aUk7hbX2mROX0I',
    appId: '1:893498280126:android:1d4581b67c118d84db76ef',
    messagingSenderId: '893498280126',
    projectId: 'lifediary-8badd',
    storageBucket: 'lifediary-8badd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDbuVLlRc5yOPob1QhGia7ooGe5bHYX3c',
    appId: '1:893498280126:ios:faf74c43e4e2f9dfdb76ef',
    messagingSenderId: '893498280126',
    projectId: 'lifediary-8badd',
    storageBucket: 'lifediary-8badd.appspot.com',
    iosBundleId: 'com.example.lifeDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDbuVLlRc5yOPob1QhGia7ooGe5bHYX3c',
    appId: '1:893498280126:ios:1aa2d2b799c50202db76ef',
    messagingSenderId: '893498280126',
    projectId: 'lifediary-8badd',
    storageBucket: 'lifediary-8badd.appspot.com',
    iosBundleId: 'com.example.lifeDiary.RunnerTests',
  );
}
